# Generated by Django 3.2.4 on 2021-09-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=80)),
                ('phone', models.IntegerField()),
                ('subject', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=200)),
                ('thumnbail', models.ImageField(upload_to='media')),
                ('video', models.FileField(upload_to='media')),
                ('speaker', models.CharField(max_length=100)),
                ('timeStamp', models.DateTimeField()),
                ('desc', models.TextField()),
                ('slug', models.CharField(max_length=200)),
            ],
        ),
    ]
