# Generated by Django 3.2.4 on 2021-09-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.CharField(default='', max_length=150),
        ),
    ]
