# Generated by Django 3.2.4 on 2021-09-04 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_service_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='slug',
            new_name='slugtwo',
        ),
    ]
