# Generated by Django 3.2.4 on 2021-09-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_slug_service_slugtwo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=250)),
                ('slugcat', models.CharField(default='', max_length=150)),
                ('desc', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
                ('video', models.FileField(upload_to='media')),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.RemoveField(
            model_name='service',
            name='video',
        ),
    ]
