# Generated by Django 3.2.4 on 2021-09-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
