# Generated by Django 3.2.4 on 2021-09-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_service_desc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Description',
        ),
        migrations.AddField(
            model_name='service',
            name='video',
            field=models.FileField(default='', upload_to='media'),
        ),
    ]
