# Generated by Django 3.2.4 on 2022-05-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210917_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350)),
                ('location', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('Engineering', 'Engineering'), ('Medical', 'Medical'), ('Nursing', 'Nursing'), ('All', 'All')], default='All', max_length=50)),
                ('photo', models.ImageField(upload_to='media')),
                ('description', models.TextField()),
                ('courses_offered', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350)),
                ('category', models.CharField(choices=[('Engineering', 'Engineering'), ('Medical', 'Medical'), ('Nursing', 'Nursing'), ('All', 'All')], default='All', max_length=50)),
                ('photo', models.ImageField(upload_to='media')),
                ('description', models.TextField()),
                ('offered_by', models.TextField()),
            ],
        ),
    ]
